/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "flandre",
  "description": "Flandre's test porject",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/img/logo.jpg"
      }
    ]
  ],
  "pages": [
    {
      "frontmatter": {},
      "regularPath": "/config.html",
      "relativePath": "config.md",
      "key": "v-6b32840c",
      "path": "/config.html"
    },
    {
      "title": "晓然老婆",
      "frontmatter": {
        "navbar": false
      },
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-479fe33c",
      "path": "/guide/",
      "headers": [
        {
          "level": 2,
          "title": "晓然老婆",
          "slug": "晓然老婆"
        }
      ]
    },
    {
      "title": "晓然老婆1",
      "frontmatter": {},
      "regularPath": "/guide/notes/one.html",
      "relativePath": "guide/notes/one.md",
      "key": "v-486d3d50",
      "path": "/guide/notes/one.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题",
          "slug": "二级标题"
        },
        {
          "level": 3,
          "title": "三级标题",
          "slug": "三级标题"
        }
      ]
    },
    {
      "title": "晓然老婆2",
      "frontmatter": {},
      "regularPath": "/guide/notes/two.html",
      "relativePath": "guide/notes/two.md",
      "key": "v-29740f18",
      "path": "/guide/notes/two.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题",
          "slug": "二级标题"
        },
        {
          "level": 3,
          "title": "三级标题",
          "slug": "三级标题"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/hero.png",
        "heroText": "Hero 标题",
        "tagline": "Hero 副标题",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-54e78529",
      "path": "/",
      "headers": [
        {
          "level": 2,
          "title": "hello vuepress",
          "slug": "hello-vuepress"
        }
      ]
    }
  ],
  "themeConfig": {
    "logo": "/img/logo.jpg",
    "nav": [
      {
        "text": "晓然老婆",
        "link": "/guide/"
      },
      {
        "text": "归档",
        "link": "/archive/"
      },
      {
        "text": "联系我",
        "link": "/contact/"
      },
      {
        "text": "友人帐",
        "link": "/friends/",
        "items": [
          {
            "text": "Grop1",
            "items": []
          },
          {
            "text": "Grop1",
            "items": []
          }
        ]
      },
      {
        "text": "赞赏",
        "link": "/appreciates/"
      },
      {
        "text": "关于",
        "link": "/about/"
      },
      {
        "text": "项目",
        "link": "/project/"
      }
    ],
    "sidebar": {
      "/guide/": [
        {
          "title": "xinshouzhinan",
          "collapsable": true,
          "children": [
            "/guide/notes/one"
          ]
        },
        {
          "title": "xinshouzhinena2",
          "collapsable": true,
          "children": [
            "/guide/notes/two"
          ]
        }
      ]
    },
    "sidebarDepth": 2,
    "lastUpdated": "Last Updated",
    "searchMaxSuggestion": 10
  }
}